

//
// +-------------------------------------------------------------------------+
// |      This file was generated by The Interactive Disassembler (IDA)      |
// |           Copyright (c) 2019 Hex-Rays, <support@hex-rays.com>           |
// +-------------------------------------------------------------------------+
//
// Input SHA256 : 67B6F303852FADB4FC6173EF13E667FA1C2D353C8B3277CB300D53A56E59F989
// Input MD5    : 6BC9A17DA6F283F9200DF725DC767E31
// Input CRC32  : 857E070B

// File Name   : Z:\home\alcopaul\Desktop\Itanium67sb\Itanium67sb.obj
// Format      : COFF (Windows-64 COFF (IA-64))

// Processor       : ia64l
// Target assembler: GNU assembler
// Byte sex        : Little endian



// Segment type: Pure code
.text



.globl .hello
.hello:
alloc r34 = ar.pfs, 0, 4, 5, 0
mov r35 = gp
mov r33 = b0
addl r14 = 0, gp;;
ld8 r14 = [r14]
addl r15 = 0, gp;;
ld8 r15 = [r15]
mov r16 = 1898
mov r17 = 95 // '_'
mov r18 = 10
mov r20 = 126 // '~'
mov r21 = 34 // '"'
mov r22 = 38 // '&'
mov r23 = 92 // '\'
mov r24 = 42 // '*'
mov r25 = 110 // 'n'
mov r26 = 33 // '!'
mov r27 = 48 // '0'
mov r28 = 36 // '$'
mov r29 = 97 // 'a'
nop.b 0

oo:
ld1 r19 = [r14], 1;;
nop.m 0
cmp.eq p1, p2 = r17, r19;;
  (p1)mov r19 = r18
  (p2)nop.i 0;;
cmp.eq p5, p6 = r20, r19;;
  (p5)mov r19 = r21
  (p6)nop.i 0;;
cmp.eq p7, p8 = r22, r19;;
  (p7)mov r19 = r23
  (p8)nop.i 0;;
cmp.eq p9, p10 = r24, r19;;
  (p9)mov r19 = r25
  (p10)nop.i 0;;
cmp.eq p11, p12 = r26, r19;;
  (p11)mov r19 = r27
  (p12)nop.i 0;;
cmp.eq p13, p14 = r28, r19;;
nop.m 0
  (p13)mov r19 = r29
  (p14)nop.b 0;;
st1 [r15] = r19, 1
adds r16 = -1, r16;;
cmp.lt p3, p4 = r0, r16
nop.m 0
nop.i 0
  (p3)br.cond.sptk.few oo
addl r36 = 0, gp;;
ld8 r36 = [r36]
addl r37 = 0, gp;;
ld8 r37 = [r37]
addl r38 = 0, gp
nop.b 0;;
ld8 r38 = [r38]
addl r39 = 0, gp
nop.b 0;;
ld8 r39 = [r39]
addl r40 = 0, gp
nop.b 0;;
// End of function .hello




sub_140:
ld8 r40 = [r48]
mov r32 = gp
br.call.sptk.many b0 = sub_140;;
mov gp = r35
mov.i ar.pfs = r34
mov b0 = r33
nop.m 0
mov r8 = 0
br.ret.sptk.many b0
// End of function sub_140

__000170:string "%s%s%s%s"<0>
__000179:string "\""<0>
__00017B:string "\\0\"\n"<0>
__000180:data8.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data8.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data8.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data8.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data8.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data8.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data8.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data8.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data8.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data8.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data8.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data8.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data8.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data8.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data8.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data8.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data8.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data8.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data8.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data8.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data8.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data8.ua 0, 0, 0, 0, 0, 0
data1 0, 0, 0
__0008EB:string "//_// bski -noconsole ./as -o I"
string "tanium67sb.o Itanium67sb.asm -x"
string "explicit_// bski -noconsole ./l"
string "d -o Itanium67sb Itanium67sb.o "
string "-lc -dynamic-linker /lib/ld-lin"
string "ux-ia64.so.2_// bski -noconsole"
string " ./Itanium67sb_//_// Itanium67s"
string "b by alCoPaUL, HAsAsIN [NaCl], "
string "beth GviLLErMo [GIMO], Zelotes "
string "ni Isa [ZnI],_// Brigada Ocho ["
string "b8]_//_// April 23-30 + May 04-"
string "06, 2026, NYC_//_.section .rdat"
string "a, ~$~, ~progbits~_.align 8_.te"
string "xt_.global hello_.proc hello_he"
string "llo:_alloc loc2 = ar.pfs, 0, 4,"
string " 5, 0_mov loc3 = gp_mov loc1 = "
string "b0_addl r14 = @ltoff(.STR2), gp"
string "_;;_ld8 r14 = [r14]_addl r15 = "
string "@ltoff(.STR18), gp_;;_ld8 r15 ="
string " [r15]_mov r16 = 1898_mov r17 ="
string " 0x5f_mov r18 = 0xa_mov r20 = 0"
string "x7e_mov r21 = 0x22_mov r22 = 0x"
string "26_mov r23 = 0x5c_mov r24 = 0x2"
string "a_mov r25 = 0x6e_mov r26 = 0x21"
string "_mov r27 = 0x30_mov r28 = 0x24_"
string "mov r29 = 0x61_oo:_ld1 r19 = [r"
string "14], 1_;;_cmp.eq p1, p2 = r17, "
string "r19_;;_(p1) mov r19 = r18_(p2) "
string "nop 0_;;_cmp.eq p5, p6 = r20, r"
string "19_;;_(p5) mov r19 = r21_(p6) n"
string "op 0_;;_cmp.eq p7, p8 = r22, r1"
string "9_;;_(p7) mov r19 = r23_(p8) no"
string "p 0_;;_cmp.eq p9, p10 = r24, r1"
string "9_;;_(p9) mov r19 = r25_(p10) n"
string "op 0_;;_cmp.eq p11, p12 = r26, "
string "r19_;;_(p11) mov r19 = r27_(p12"
string ") nop 0_;;_cmp.eq p13, p14 = r2"
string "8, r19_;;_(p13) mov r19 = r29_("
string "p14) nop 0_;;_st1 [r15] = r19, "
string "1_add r16 = -1, r16_;;_cmp.gt p"
string "3, p4 = r16, r0_(p3) br.cond.sp"
string "tk oo_addl out0 = @ltoff(.STR3)"
string ", gp_;;_ld8 out0 = [out0]_addl "
string "out1 = @ltoff(.STR18), gp_;;_ld"
string "8 out1 = [out1]_addl out2 = @lt"
string "off(.STR23), gp_;;_ld8 out2 = ["
string "out2]_addl out3 = @ltoff(.STR2)"
string ", gp_;;_ld8 out3 = [out3]_addl "
string "out4 = @ltoff(.STR214), gp_;;_l"
string "d8 out4 = [out4]_mov loc0 = gp_"
string "br.call.sptk.many b0 = printf_;"
string ";_mov gp = loc3_mov ar.pfs = lo"
string "c2_mov b0 = loc1_mov ret0 = 0_b"
string "r.ret.sptk.many b0_.endp hello_"
string ".global printf_.type printf, @f"
string "unction_.STR3:_stringz ~%s%s%s%"
string "s~_.STR23:_stringz ~&~~_.STR214"
string ":_stringz ~&&!&~&*~_.STR18:_str"
string "ingz ~~_.skip 1898_.STR2:_strin"
string "gz "<0>
data1 0
.align 3


// Segment type: Zero-length
.data


// Segment type: Zero-length
.bss


// Segment type: Zero-length
.sdata


// Segment type: Zero-length
.sbss


// Segment type: Zero-length
.data// .xdata


// Segment type: Zero-length
.rdata


// Segment type: Pure data
.rdata
// COMDAT (pick no duplicate)
.globl hello
hello:data1    0 // Unknown fixup
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0 // Unknown fixup
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0


// Segment type: Externs
.extern _gp
.extern .printf

// end
