

//
// +-------------------------------------------------------------------------+
// |      This file was generated by The Interactive Disassembler (IDA)      |
// |           Copyright (c) 2019 Hex-Rays, <support@hex-rays.com>           |
// +-------------------------------------------------------------------------+
//
// Input SHA256 : EC48D3673908DBF92D7276FC8E548CBBC52C4E1A856E80115439F8979D751AF8
// Input MD5    : 41CE32DEC7D409B0AB7054230AA2A744
// Input CRC32  : C3954A28

// File Name   : Z:\home\alcopaul\Desktop\Itanium67sb\Itanium67sb.exe
// Format      : Portable executable for IA64 (PE)
// Imagebase   : 140000000
// Timestamp   : 69FB43D0 (Wed May 06 13:36:16 2026)
// Section 1. (virtual address 00002000)
// Virtual size                  : 00001050 (   4176.)
// Section size in file          : 00001200 (   4608.)
// Offset to raw data for section: 00000400
// Flags 60000020: Text Executable Readable
// Alignment     : default

// Processor       : ia64l
// Target assembler: GNU assembler
// Byte sex        : Little endian



// Segment type: Pure code
.text



.globl start
start:
alloc r34 = ar.pfs, 0, 4, 5, 0
mov r35 = gp
mov r33 = b0
addl r14 = -2097144, gp;;// off_140006008 // "//_// bski -noconsole ./as -o Itanium67"...
ld8 r14 = [r14]         // aBskiNoconsoleA // "//_// bski -noconsole ./as -o Itanium67"...
addl r15 = -2097128, gp;;// off_140006018
ld8 r15 = [r15]         // dword_140002180
mov r16 = 1898
mov r17 = 95 // '_'
mov r18 = 10
mov r20 = 126 // '~'
mov r21 = 34 // '"'
mov r22 = 38 // '&'
mov r23 = 92 // '\'
mov r24 = 42 // '*'
mov r25 = 110 // 'n'
mov r26 = 33 // '!'
mov r27 = 48 // '0'
mov r28 = 36 // '$'
mov r29 = 97 // 'a'
nop.b 0

loc_140002070:
ld1 r19 = [r14], 1;;
nop.m 0
cmp.eq p1, p2 = r17, r19;;
  (p1)mov r19 = r18
  (p2)nop.i 0;;
cmp.eq p5, p6 = r20, r19;;
  (p5)mov r19 = r21
  (p6)nop.i 0;;
cmp.eq p7, p8 = r22, r19;;
  (p7)mov r19 = r23
  (p8)nop.i 0;;
cmp.eq p9, p10 = r24, r19;;
  (p9)mov r19 = r25
  (p10)nop.i 0;;
cmp.eq p11, p12 = r26, r19;;
  (p11)mov r19 = r27
  (p12)nop.i 0;;
cmp.eq p13, p14 = r28, r19;;
nop.m 0
  (p13)mov r19 = r29
  (p14)nop.b 0;;
st1 [r15] = r19, 1
adds r16 = -1, r16;;
cmp.lt p3, p4 = r0, r16
nop.m 0
nop.i 0
  (p3)br.cond.sptk.few loc_140002070
addl r36 = -2097120, gp;;// off_140006020 // "%s%s%s%s"
ld8 r36 = [r36]         // aSSSS // "%s%s%s%s"
addl r37 = -2097128, gp;;// off_140006018
ld8 r37 = [r37]         // dword_140002180
addl r38 = -2097136, gp // off_140006010 // "\""
nop.b 0;;
ld8 r38 = [r38]         // asc_140002179 // "\""
addl r39 = -2097144, gp // off_140006008 // "//_// bski -noconsole ./as -o Itanium67"...
nop.b 0;;
ld8 r39 = [r39]         // aBskiNoconsoleA // "//_// bski -noconsole ./as -o Itanium67"...
addl r40 = -2097152, gp // off_140006000 // "\\0\"\n"
nop.b 0;;
ld8 r40 = [r40]         // a0 // "\\0\"\n"
mov r32 = gp
br.call.sptk.many b0 = .printf;;
mov gp = r35
mov.i ar.pfs = r34
mov b0 = r33
nop.m 0
mov r8 = 0
br.ret.sptk.many b0
// End of function start

aSSSS:string "%s%s%s%s"<0>
asc_140002179:string "\""<0>
a0:string "\\0\"\n"<0>
dword_140002180:data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0
data1 0, 0, 0
aBskiNoconsoleA:string "//_// bski -noconsole ./as -o I"
string "tanium67sb.o Itanium67sb.asm -x"
string "explicit_// bski -noconsole ./l"
string "d -o Itanium67sb Itanium67sb.o "
string "-lc -dynamic-linker /lib/ld-lin"
string "ux-ia64.so.2_// bski -noconsole"
string " ./Itanium67sb_//_// Itanium67s"
string "b by alCoPaUL, HAsAsIN [NaCl], "
string "beth GviLLErMo [GIMO], Zelotes "
string "ni Isa [ZnI],_// Brigada Ocho ["
string "b8]_//_// April 23-30 + May 04-"
string "06, 2026, NYC_//_.section .rdat"
string "a, ~$~, ~progbits~_.align 8_.te"
string "xt_.global hello_.proc hello_he"
string "llo:_alloc loc2 = ar.pfs, 0, 4,"
string " 5, 0_mov loc3 = gp_mov loc1 = "
string "b0_addl r14 = @ltoff(.STR2), gp"
string "_;;_ld8 r14 = [r14]_addl r15 = "
string "@ltoff(.STR18), gp_;;_ld8 r15 ="
string " [r15]_mov r16 = 1898_mov r17 ="
string " 0x5f_mov r18 = 0xa_mov r20 = 0"
string "x7e_mov r21 = 0x22_mov r22 = 0x"
string "26_mov r23 = 0x5c_mov r24 = 0x2"
string "a_mov r25 = 0x6e_mov r26 = 0x21"
string "_mov r27 = 0x30_mov r28 = 0x24_"
string "mov r29 = 0x61_oo:_ld1 r19 = [r"
string "14], 1_;;_cmp.eq p1, p2 = r17, "
string "r19_;;_(p1) mov r19 = r18_(p2) "
string "nop 0_;;_cmp.eq p5, p6 = r20, r"
string "19_;;_(p5) mov r19 = r21_(p6) n"
string "op 0_;;_cmp.eq p7, p8 = r22, r1"
string "9_;;_(p7) mov r19 = r23_(p8) no"
string "p 0_;;_cmp.eq p9, p10 = r24, r1"
string "9_;;_(p9) mov r19 = r25_(p10) n"
string "op 0_;;_cmp.eq p11, p12 = r26, "
string "r19_;;_(p11) mov r19 = r27_(p12"
string ") nop 0_;;_cmp.eq p13, p14 = r2"
string "8, r19_;;_(p13) mov r19 = r29_("
string "p14) nop 0_;;_st1 [r15] = r19, "
string "1_add r16 = -1, r16_;;_cmp.gt p"
string "3, p4 = r16, r0_(p3) br.cond.sp"
string "tk oo_addl out0 = @ltoff(.STR3)"
string ", gp_;;_ld8 out0 = [out0]_addl "
string "out1 = @ltoff(.STR18), gp_;;_ld"
string "8 out1 = [out1]_addl out2 = @lt"
string "off(.STR23), gp_;;_ld8 out2 = ["
string "out2]_addl out3 = @ltoff(.STR2)"
string ", gp_;;_ld8 out3 = [out3]_addl "
string "out4 = @ltoff(.STR214), gp_;;_l"
string "d8 out4 = [out4]_mov loc0 = gp_"
string "br.call.sptk.many b0 = printf_;"
string ";_mov gp = loc3_mov ar.pfs = lo"
string "c2_mov b0 = loc1_mov ret0 = 0_b"
string "r.ret.sptk.many b0_.endp hello_"
string ".global printf_.type printf, @f"
string "unction_.STR3:_stringz ~%s%s%s%"
string "s~_.STR23:_stringz ~&~~_.STR214"
string ":_stringz ~&&!&~&*~_.STR18:_str"
string "ingz ~~_.skip 1898_.STR2:_strin"
string "gz "<0>
data4.ua 0
data8.ua 0



.printf:
addl r2 = -2088960, gp;;// printf
ld8 r2 = [r2]           // printf
nop.i 0;;
ld8 r3 = [r2], 8;;      // printf
ld8 gp = [r2]           // printf
mov b6 = r3
nop.m 0
nop.i 0
br.few b6
// End of function .printf

.align 9
.space 0xE00

// Section 2. (virtual address 00004000)
// Virtual size                  : 00000060 (     96.)
// Section size in file          : 00000200 (    512.)
// Offset to raw data for section: 00001600
// Flags 40000040: Data Readable
// Alignment     : default

// Segment type: Pure data
.rdata
start_ptr:data8.ua start
data8.ua 0x140206000
__IMPORT_DESCRIPTOR_MSVCR100:data4.ua @imagerel off_140004038 // Import Name Table
data4.ua 0              // Time stamp
data4.ua 0              // Forwarder Chain
data4.ua @imagerel aMsvcr100Dll // DLL Name
data4.ua @imagerel printf // Import Address Table
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
//
// Import names for MSVCR100.dll
//
off_140004038:data8.ua @imagerel word_140004048
data8.ua 0
word_140004048:data2.ua 0x4FB
string "printf"<0>
.align 1
aMsvcr100Dll:string "MSVCR100.dll"<0>
.align 0xD

// Section 3. (virtual address 00006000)
// Virtual size                  : 00000028 (     40.)
// Section size in file          : 00000200 (    512.)
// Offset to raw data for section: 00001800
// Flags 40000040: Data Readable
// Alignment     : default

// Segment type: Pure data
.data// .srdata
off_140006000:data8.ua a0 // "\\0\"\n"
off_140006008:data8.ua aBskiNoconsoleA // "//_// bski -noconsole ./as -o Itanium67"...
off_140006010:data8.ua asc_140002179 // "\""
off_140006018:data8.ua dword_140002180
off_140006020:data8.ua aSSSS // "%s%s%s%s"
.align 0xD

// Section 4. (virtual address 00008000)
// Virtual size                  : 00000010 (     16.)
// Section size in file          : 00000200 (    512.)
// Offset to raw data for section: 00001A00
// Flags C0000040: Data Readable Writable
// Alignment     : default
//
// Imports from MSVCR100.dll
//

// Segment type: Externs
.extern printf



// Segment type: Pure data
.sdata
.align 0xD

// end start
