

//
// +-------------------------------------------------------------------------+
// |      This file was generated by The Interactive Disassembler (IDA)      |
// |           Copyright (c) 2019 Hex-Rays, <support@hex-rays.com>           |
// +-------------------------------------------------------------------------+
//
// Input SHA256 : D067B279740BAB6A3EE3A58F62604DF1AF22FBFE83F8F1E0F002F08A84324B44
// Input MD5    : E1AA41AE6F1E2940E03C2EBC64657A21
// Input CRC32  : A1794D3A

// File Name   : Z:\home\alcopaul\Desktop\yo\Itanium67.exe
// Format      : Portable executable for IA64 (PE)
// Imagebase   : 140000000
// Timestamp   : 69FAA06E (Wed May 06 01:59:10 2026)
// Section 1. (virtual address 00002000)
// Virtual size                  : 00000F90 (   3984.)
// Section size in file          : 00001000 (   4096.)
// Offset to raw data for section: 00000400
// Flags 60000020: Text Executable Readable
// Alignment     : default

// Processor       : ia64l
// Target assembler: GNU assembler
// Byte sex        : Little endian



// Segment type: Pure code
.text



.globl start
start:
alloc r34 = ar.pfs, 0, 4, 5, 0
mov r35 = gp
mov r33 = b0
addl r14 = -2097144, gp;;// off_140006008 // "//_// bski -noconsole ./as -o Itanium67"...
ld8 r14 = [r14]         // aBskiNoconsoleA // "//_// bski -noconsole ./as -o Itanium67"...
addl r15 = -2097128, gp;;// off_140006018
ld8 r15 = [r15]         // dword_140002180
mov r16 = 1800
mov r17 = 95 // '_'
mov r18 = 10
mov r20 = 126 // '~'
mov r21 = 34 // '"'
mov r22 = 38 // '&'
mov r23 = 92 // '\'
mov r24 = 42 // '*'
mov r25 = 110 // 'n'
mov r26 = 33 // '!'
mov r27 = 48 // '0'
mov r28 = 36 // '$'
mov r29 = 97 // 'a'
nop.b 0

loc_140002070:
ld1 r19 = [r14], 1;;
nop.m 0
cmp.eq p1, p2 = r17, r19;;
  (p1)mov r19 = r18
  (p2)nop.i 0;;
cmp.eq p5, p6 = r20, r19;;
  (p5)mov r19 = r21
  (p6)nop.i 0;;
cmp.eq p7, p8 = r22, r19;;
  (p7)mov r19 = r23
  (p8)nop.i 0;;
cmp.eq p9, p10 = r24, r19;;
  (p9)mov r19 = r25
  (p10)nop.i 0;;
cmp.eq p11, p12 = r26, r19;;
  (p11)mov r19 = r27
  (p12)nop.i 0;;
cmp.eq p13, p14 = r28, r19;;
nop.m 0
  (p13)mov r19 = r29
  (p14)nop.b 0;;
st1 [r15] = r19, 1
adds r16 = -1, r16;;
cmp.lt p3, p4 = r0, r16
nop.m 0
nop.i 0
  (p3)br.cond.sptk.few loc_140002070
addl r36 = -2097120, gp;;// off_140006020 // "%s%s%s%s"
ld8 r36 = [r36]         // aSSSS // "%s%s%s%s"
addl r37 = -2097128, gp;;// off_140006018
ld8 r37 = [r37]         // dword_140002180
addl r38 = -2097136, gp // off_140006010 // "\""
nop.b 0;;
ld8 r38 = [r38]         // asc_140002179 // "\""
addl r39 = -2097144, gp // off_140006008 // "//_// bski -noconsole ./as -o Itanium67"...
nop.b 0;;
ld8 r39 = [r39]         // aBskiNoconsoleA // "//_// bski -noconsole ./as -o Itanium67"...
addl r40 = -2097152, gp // off_140006000 // "\\0\"\n"
nop.b 0;;
ld8 r40 = [r40]         // a0 // "\\0\"\n"
mov r32 = gp
br.call.sptk.many b0 = .printf
mov gp = r35
mov.i ar.pfs = r34
mov b0 = r33
nop.m 0
mov r8 = 0
br.ret.sptk.many b0
// End of function start

aSSSS:string "%s%s%s%s"<0>
asc_140002179:string "\""<0>
a0:string "\\0\"\n"<0>
dword_140002180:data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data1 0
aBskiNoconsoleA:string "//_// bski -noconsole ./as -o I"
string "tanium67.o Itanium67.asm_// bsk"
string "i -noconsole ./ld -o Itanium67 "
string "Itanium67.o -lc -dynamic-linker"
string " /lib/ld-linux-ia64.so.2_// bsk"
string "i -noconsole ./Itanium67_//_// "
string "Itanium67 by alCoPaUL, HAsAsIN "
string "[NaCl], beth GviLLErMo [GIMO], "
string "Zelotes ni Isa [ZnI],_// Brigad"
string "a Ocho [b8]_//_// April 23-30 +"
string " May 04-05, 2026, NYC_//_.secti"
string "on .rdata, ~$~, ~progbits~_.ali"
string "gn 8_.text_.global hello_.proc "
string "hello_hello:_alloc loc2 = ar.pf"
string "s, 0, 4, 5, 0_mov loc3 = gp_mov"
string " loc1 = b0_addl r14 = @ltoff(.S"
string "TR2), gp_ld8 r14 = [r14]_addl r"
string "15 = @ltoff(.STR18), gp_ld8 r15"
string " = [r15]_mov r16 = 1800_mov r17"
string " = 0x5f_mov r18 = 0xa_mov r20 ="
string " 0x7e_mov r21 = 0x22_mov r22 = "
string "0x26_mov r23 = 0x5c_mov r24 = 0"
string "x2a_mov r25 = 0x6e_mov r26 = 0x"
string "21_mov r27 = 0x30_mov r28 = 0x2"
string "4_mov r29 = 0x61_oo:_ld1 r19 = "
string "[r14], 1_cmp.eq p1, p2 = r17, r"
string "19_(p1) mov r19 = r18_(p2) nop "
string "0_cmp.eq p5, p6 = r20, r19_(p5)"
string " mov r19 = r21_(p6) nop 0_cmp.e"
string "q p7, p8 = r22, r19_(p7) mov r1"
string "9 = r23_(p8) nop 0_cmp.eq p9, p"
string "10 = r24, r19_(p9) mov r19 = r2"
string "5_(p10) nop 0_cmp.eq p11, p12 ="
string " r26, r19_(p11) mov r19 = r27_("
string "p12) nop 0_cmp.eq p13, p14 = r2"
string "8, r19_(p13) mov r19 = r29_(p14"
string ") nop 0_st1 [r15] = r19, 1_add "
string "r16 = -1, r16_cmp.gt p3, p4 = r"
string "16, r0_(p3) br.cond.sptk oo_add"
string "l out0 = @ltoff(.STR3), gp_ld8 "
string "out0 = [out0]_addl out1 = @ltof"
string "f(.STR18), gp_ld8 out1 = [out1]"
string "_addl out2 = @ltoff(.STR23), gp"
string "_ld8 out2 = [out2]_addl out3 = "
string "@ltoff(.STR2), gp_ld8 out3 = [o"
string "ut3]_addl out4 = @ltoff(.STR214"
string "), gp_ld8 out4 = [out4]_mov loc"
string "0 = gp_br.call.sptk.many b0 = p"
string "rintf_mov gp = loc3_mov ar.pfs "
string "= loc2_mov b0 = loc1_mov ret0 ="
string " 0_br.ret.sptk.many b0_.endp he"
string "llo_.global printf_.type printf"
string ", @function_.STR3:_stringz ~%s%"
string "s%s%s~_.STR23:_stringz ~&~~_.ST"
string "R214:_stringz ~&&!&~&*~_.STR18:"
string "_stringz ~~_.skip 1800_.STR2:_s"
string "tringz "<0>
data1 0, 0, 0, 0, 0, 0, 0



.printf:
addl r2 = -2088960, gp;;// printf
ld8 r2 = [r2]           // printf
nop.i 0;;
ld8 r3 = [r2], 8;;      // printf
ld8 gp = [r2]           // printf
mov b6 = r3
nop.m 0
nop.i 0
br.few b6
// End of function .printf

.align 7
.space 0x1000

// Section 2. (virtual address 00004000)
// Virtual size                  : 00000060 (     96.)
// Section size in file          : 00000200 (    512.)
// Offset to raw data for section: 00001400
// Flags 40000040: Data Readable
// Alignment     : default

// Segment type: Pure data
.rdata
start_ptr:data8.ua start
data8.ua 0x140206000
__IMPORT_DESCRIPTOR_MSVCR100:data4.ua @imagerel off_140004038 // Import Name Table
data4.ua 0              // Time stamp
data4.ua 0              // Forwarder Chain
data4.ua @imagerel aMsvcr100Dll // DLL Name
data4.ua @imagerel printf // Import Address Table
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
//
// Import names for MSVCR100.dll
//
off_140004038:data8.ua @imagerel word_140004048
data8.ua 0
word_140004048:data2.ua 0x4FB
string "printf"<0>
.align 1
aMsvcr100Dll:string "MSVCR100.dll"<0>
.align 0xD

// Section 3. (virtual address 00006000)
// Virtual size                  : 00000028 (     40.)
// Section size in file          : 00000200 (    512.)
// Offset to raw data for section: 00001600
// Flags 40000040: Data Readable
// Alignment     : default

// Segment type: Pure data
.data// .srdata
off_140006000:data8.ua a0 // "\\0\"\n"
off_140006008:data8.ua aBskiNoconsoleA // "//_// bski -noconsole ./as -o Itanium67"...
off_140006010:data8.ua asc_140002179 // "\""
off_140006018:data8.ua dword_140002180
off_140006020:data8.ua aSSSS // "%s%s%s%s"
.align 0xD

// Section 4. (virtual address 00008000)
// Virtual size                  : 00000010 (     16.)
// Section size in file          : 00000200 (    512.)
// Offset to raw data for section: 00001800
// Flags C0000040: Data Readable Writable
// Alignment     : default
//
// Imports from MSVCR100.dll
//

// Segment type: Externs
.extern printf



// Segment type: Pure data
.sdata
.align 0xD

// end start
