

//
// +-------------------------------------------------------------------------+
// |      This file was generated by The Interactive Disassembler (IDA)      |
// |           Copyright (c) 2019 Hex-Rays, <support@hex-rays.com>           |
// +-------------------------------------------------------------------------+
//
// Input SHA256 : 346DCB757C41602304375E8C23B462673A8ACDA9199CE48DDED15F863256A542
// Input MD5    : 2DAA990D3BE3703FA4740EA99C9E7A4C
// Input CRC32  : CABEE338

// File Name   : Z:\home\alcopaul\Desktop\VVV\jjoy.obj
// Format      : COFF (Windows-64 COFF (IA-64))
// includelib "LIBCMT"
// includelib "OLDNAMES"

// Processor       : ia64l
// Target assembler: GNU assembler
// Byte sex        : Little endian


// ===========================================================================

// Segment type: Pure data
                .data
_SG2075:        string "\"lez go\\\"\\\\n there,\\\""<0>
                .align 3

// ===========================================================================

// Segment type: Pure data
                .sdata
_SG2081:        string "%s %s"<0>
                .align 5

// ===========================================================================

// Segment type: Pure code
                .text

// =============== S U B R O U T I N E =======================================


                .globl .main
.main:                                  // DATA XREF: .pdata:_T2095↓o
                alloc r33 = ar.pfs, 0, 3, 3, 0 // $LN6@main
                adds sp = -48, sp
                mov r32 = b0
                addl r31 = 0, gp
                mov r34 = gp;;
                adds r29 = 56, sp // '8'
                ld8 r30 = [r31]
                ld8.nta r2 = [sp]
                nop.b 0;;
                st8 [r29] = r30;;
                addl r28 = 0, gp
                adds r26 = 16, sp;;
                ld8 r27 = [r28];;
                st8 [r26] = r27
                nop.i 0;;
                adds r25 = 24, sp;;
                st4 [r25] = r0
                nop.i 0
                nop.m 0
                nop.m 0
                br.few loc_C0;;
// ---------------------------------------------------------------------------

loc_90:                                 // CODE XREF: .main+11C↓j
                adds r22 = 24, sp
                adds r19 = 24, sp
                nop.b 0;;
                ld4 r21 = [r22];;
                adds r20 = 1, r21
                nop.i 0;;
                st4 [r19] = r20
                nop.m 0
                nop.b 0;;

loc_C0:                                 // CODE XREF: .main+6C↑j
                adds r18 = 24, sp;;
                ld4 r17 = [r18]
                nop.i 0;;
                cmp4.lt.unc p14, p15 = 21, r17
                nop.m 0
  (p14)          br.cond.dptk.few loc_140;;
                adds r16 = 24, sp
                adds r10 = 16, sp
                adds r31 = 24, sp
                adds r28 = 32, sp;; // ' '
                ld4 r15 = [r16]
                nop.i 0
                ld8 r9 = [r10];;
                ld4 r30 = [r31]
                sxt4 r11 = r15;;
                add r8 = r9, r11
                sxt4 r29 = r30;;
                add r27 = r28, r29
                ld1 r26 = [r8];;
                st1 [r27] = r26
                nop.i 0;;
                nop.m 0
                nop.m 0
                br.few loc_90;;
// ---------------------------------------------------------------------------

loc_140:                                // CODE XREF: .main+BC↑j
                adds r25 = 16, sp
                addl r35 = 0, gp
                adds r37 = 32, sp;; // ' '
// End of function .main


// =============== S U B R O U T I N E =======================================


sub_150:                                // CODE XREF: sub_150+C↓p
                ld8 r36 = [r25]
                nop.m 0
                br.call.sptk.few b0 = sub_150;;
                mov gp = r34;;
                adds r22 = 56, sp // '8'
                nop.i 0;;
// End of function sub_150


// =============== S U B R O U T I N E =======================================


sub_170:                                // CODE XREF: sub_170+C↓p
                ld8 r35 = [r23]
                nop.m 0
                br.call.sptk.few b0 = sub_170;;
                mov gp = r34
                mov r8 = r0;;
                mov b0 = r32;;
                adds sp = 48, sp // '0'
                mov.i ar.pfs = r33

loc_19C:                                // DATA XREF: .pdata:00000000000001B4↓o
                br.ret.sptk.many b0;;
// End of function sub_170


// ===========================================================================

// Segment type: Pure data
                .rdata
// COMDAT (pick no duplicate)
                .globl main
main:           data1    0 // Unknown fixup
                data1    0
                data1    0
                data1    0
                data1    0
                data1    0
                data1    0
                data1    0
                .align 4

// ===========================================================================

// Segment type: Pure data
                .data// .pdata
_T2095:         data2.ua .main
                .align 2
                data2.ua loc_19C+4
                .align 3
                data2.ua _T2093
                .align 2
                .align 5

// ===========================================================================

// Segment type: Pure data
                .data// .xdata
_T2093:         data1    3              // DATA XREF: .pdata:00000000000001B8↑o
                data1    0
                data1    3
                data1    0
                data1    3
                data1    0
                data1    0
                data1    0
                data1  0xA
                data1 0xE6
                data1    0
                data1 0xB1
                data1 0x21 // !
                data1 0xE0
                data1    1
                data1    3
                data1 0xE4
                data1    2
                data1 0xB0
                data1 0xA0
                data1 0x61 // a
                data1 0x3E // >
                data1 0x81
                data1 0xC0
                data1    2
                data1    0
                data1    0
                data1    0
                data1    0
                data1    0
                data1    0
                data1    0
                data2.ua __GSHandlerCheck
                .align 2
                data1    8
                data1    0
                data1    0
                data1    0

// ===========================================================================

// Segment type: Externs
                .extern .printf
                .extern __security_cookie
                .extern __GSHandlerCheck
                                        // DATA XREF: .xdata:00000000000001E0↑o
                .extern .__security_check_cookie
                .extern _gp

                // end
