

//
// +-------------------------------------------------------------------------+
// |      This file was generated by The Interactive Disassembler (IDA)      |
// |           Copyright (c) 2019 Hex-Rays, <support@hex-rays.com>           |
// +-------------------------------------------------------------------------+
//
// Input SHA256 : DBDD8BF1CF972802318C9E74029E392B9518FD2DB9797116D37596D5918FA190
// Input MD5    : A61A8D5AD59D9C684D355D1AD7AFC84E
// Input CRC32  : CBE06239

// File Name   : Z:\home\alcopaul\Desktop\yo\qias64.exe
// Format      : Portable executable for IA64 (PE)
// Imagebase   : 140000000
// Timestamp   : 69FA5117 (Tue May 05 20:20:39 2026)
// Section 1. (virtual address 00002000)
// Virtual size                  : 00000B70 (   2928.)
// Section size in file          : 00000C00 (   3072.)
// Offset to raw data for section: 00000400
// Flags 60000020: Text Executable Readable
// Alignment     : default

// Processor       : ia64l
// Target assembler: GNU assembler
// Byte sex        : Little endian



// Segment type: Pure code
.text



.globl start
start:
alloc r34 = ar.pfs, 0, 4, 5, 0
mov r35 = gp
mov r33 = b0
addl r14 = -2097144, gp;;// off_140006008 // "//_// bski -noconsole ./as -o qia64.o q"...
ld8 r14 = [r14]         // aBskiNoconsoleA // "//_// bski -noconsole ./as -o qia64.o q"...
addl r15 = -2097128, gp;;// off_140006018
ld8 r15 = [r15]         // dword_140002100
mov r16 = 1300
mov r17 = 95 // '_'
nop.m 0
mov r18 = 10
nop.b 0

loc_140002040:
ld1 r19 = [r14], 1;;    // off_140006008 // "//_// bski -noconsole ./as -o qia64.o q"...
nop.m 0
cmp.eq p1, p2 = r17, r19;;
nop.m 0
  (p1)mov r19 = r18
  (p2)nop.b 0;;
st1 [r15] = r19, 1      // off_140006018
adds r16 = -1, r16;;
cmp.lt p3, p4 = r0, r16
nop.m 0
nop.i 0
  (p3)br.cond.sptk.few loc_140002040
addl r36 = -2097120, gp;;// off_140006020 // "%s%s%s%s"
ld8 r36 = [r36]         // aSSSS // "%s%s%s%s"
addl r37 = -2097128, gp;;// off_140006018
ld8 r37 = [r37]         // dword_140002100
addl r38 = -2097136, gp // off_140006010 // "\""
nop.b 0;;
ld8 r38 = [r38]         // asc_1400020F9 // "\""
addl r39 = -2097144, gp // off_140006008 // "//_// bski -noconsole ./as -o qia64.o q"...
nop.b 0;;
ld8 r39 = [r39]         // aBskiNoconsoleA // "//_// bski -noconsole ./as -o qia64.o q"...
addl r40 = -2097152, gp // off_140006000 // "\\0\"\n"
nop.b 0;;
ld8 r40 = [r40]         // a0 // "\\0\"\n"
mov r32 = gp
br.call.sptk.many b0 = .printf
mov gp = r35
mov.i ar.pfs = r34
mov b0 = r33
nop.m 0
mov r8 = 0
br.ret.sptk.many b0
// End of function start

aSSSS:string "%s%s%s%s"<0>
asc_1400020F9:string "\""<0>
a0:string "\\0\"\n"<0>
dword_140002100:data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
data4.ua 0, 0, 0, 0, 0, 0
data1 0
aBskiNoconsoleA:string "//_// bski -noconsole ./as -o q"
string "ia64.o qia64.asm_// bski -nocon"
string "sole ./ld -o qia64 qia64.o -lc "
string "-dynamic-linker /lib/ld-linux-i"
string "a64.so.2_// bski -noconsole ./q"
string "ia64_//_// qia64 beta.alpha.gam"
string "ma by alCoPaUL, HAsAsIN [NaCl],"
string " beth GviLLErMo [GIMO], Zelotes"
string " ni Isa [ZnI],_// Brigada Ocho "
string "[b8]_// April 23-30 & May 04, 2"
string "026, NYC_//_.section .rdata, \""
string "a\", \"progbits\"_.align 8_.tex"
string "t_.global hello_.proc hello_hel"
string "lo:_alloc loc2 = ar.pfs, 0, 4, "
string "5, 0_mov loc3 = gp_mov loc1 = b"
string "0_addl r14 = @ltoff(.STR2), gp_"
string "ld8 r14 = [r14]_addl r15 = @lto"
string "ff(.STR18), gp_ld8 r15 = [r15]_"
string "mov r16 = 1300_mov r17 = 0x5f_m"
string "ov r18 = 0xa_oo:_ld1 r19 = [r14"
string "], 1_cmp.eq p1, p2 = r17, r19_("
string "p1) mov r19 = r18_(p2) nop 0_st"
string "1 [r15] = r19, 1_add r16 = -1, "
string "r16_cmp.gt p3, p4 = r16, r0_(p3"
string ") br.cond.sptk oo_addl out0 = @"
string "ltoff(.STR3), gp_ld8 out0 = [ou"
string "t0]_addl out1 = @ltoff(.STR18),"
string " gp_ld8 out1 = [out1]_addl out2"
string " = @ltoff(.STR23), gp_ld8 out2 "
string "= [out2]_addl out3 = @ltoff(.ST"
string "R2), gp_ld8 out3 = [out3]_addl "
string "out4 = @ltoff(.STR214), gp_ld8 "
string "out4 = [out4]_mov loc0 = gp_br."
string "call.sptk.many b0 = printf_mov "
string "gp = loc3_mov ar.pfs = loc2_mov"
string " b0 = loc1_mov ret0 = 0_br.ret."
string "sptk.many b0_.endp hello_.globa"
string "l printf_.type printf, @functio"
string "n_.STR3:_stringz \"%s%s%s%s\"_."
string "STR18:_stringz \"\\\"\"_.STR214"
string ":_stringz \"\\\\0\\\"\\n\"_.STR"
string "18:_stringz \"\"_.skip 1300_.ST"
string "R2:_stringz "<0>
data1 0, 0, 0
data8.ua 0, 0, 0



.printf:
addl r2 = -2088960, gp;;// printf
ld8 r2 = [r2]           // printf
nop.i 0;;
ld8 r3 = [r2], 8;;      // printf
ld8 gp = [r2]           // printf
mov b6 = r3
nop.m 0
nop.i 0
br.few b6
// End of function .printf

.align 8
.space 0x1400

// Section 2. (virtual address 00004000)
// Virtual size                  : 00000060 (     96.)
// Section size in file          : 00000200 (    512.)
// Offset to raw data for section: 00001000
// Flags 40000040: Data Readable
// Alignment     : default

// Segment type: Pure data
.rdata
start_ptr:data8.ua start
data8.ua 0x140206000
__IMPORT_DESCRIPTOR_MSVCR100:data4.ua @imagerel off_140004038 // Import Name Table
data4.ua 0              // Time stamp
data4.ua 0              // Forwarder Chain
data4.ua @imagerel aMsvcr100Dll // DLL Name
data4.ua @imagerel printf // Import Address Table
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
data1    0
//
// Import names for MSVCR100.dll
//
off_140004038:data8.ua @imagerel word_140004048
data8.ua 0
word_140004048:data2.ua 0x4FB
string "printf"<0>
.align 1
aMsvcr100Dll:string "MSVCR100.dll"<0>
.align 0xD

// Section 3. (virtual address 00006000)
// Virtual size                  : 00000028 (     40.)
// Section size in file          : 00000200 (    512.)
// Offset to raw data for section: 00001200
// Flags 40000040: Data Readable
// Alignment     : default

// Segment type: Pure data
.data// .srdata
off_140006000:data8.ua a0 // "\\0\"\n"
off_140006008:data8.ua aBskiNoconsoleA // "//_// bski -noconsole ./as -o qia64.o q"...
off_140006010:data8.ua asc_1400020F9 // "\""
off_140006018:data8.ua dword_140002100
off_140006020:data8.ua aSSSS // "%s%s%s%s"
.align 0xD

// Section 4. (virtual address 00008000)
// Virtual size                  : 00000010 (     16.)
// Section size in file          : 00000200 (    512.)
// Offset to raw data for section: 00001400
// Flags C0000040: Data Readable Writable
// Alignment     : default
//
// Imports from MSVCR100.dll
//

// Segment type: Externs
.extern printf



// Segment type: Pure data
.sdata
.align 0xD

// end start
